name: CI

on:
  push:
    branches:
      - master
      # Feature branches beginning with "feature."
      - feature.*
  pull_request:

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec tests/

  unit_tests_ts:
    name: Unit tests Typescript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm test

  dart_sass:
    name: Dart Sass
    runs-on: ubuntu-latest
    if: "github.event_name != 'pull_request' || !contains('skip dart-sass', github.event.pull_request.body)"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Dart
        uses: cedx/setup-dart@v2
        with:
          release-channel: stable

      - name: Install dart-sass
        run: |
          GITHUB_REF=${PR_REF:-$CURRENT_REF}
          if [[ "$GITHUB_REF" == refs/heads/feature.* ]]; then branch="${GITHUB_REF:11}"; else branch=master; fi
          git clone https://github.com/sass/dart-sass.git ../dart-sass --depth 1 --branch "$branch"
          (cd ../dart-sass; dart pub get)
        env:
          PR_REF: "${{ github.base_ref }}"
          CURRENT_REF: "${{ github.ref }}"

      - name: Run specs
        run: bundle exec sass-spec.rb --dart ../dart-sass

  libsass:
    name: LibSass
    runs-on: ubuntu-latest
    if: "github.event_name != 'pull_request' || !contains('skip libsass', github.event.pull_request.body)"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install sassc
        run: |
          export SASS_LIBSASS_PATH=$BUILD_DIR/../libsass
          export SASS_SASSC_PATH=$BUILD_DIR/../sassc
          git clone https://github.com/sass/libsass.git $SASS_LIBSASS_PATH
          (cd $SASS_LIBSASS_PATH; git checkout $GITISH)
          git clone https://github.com/sass/sassc.git $SASS_SASSC_PATH
          (cd $SASS_SASSC_PATH; git checkout $GITISH)
          make -C $SASS_SASSC_PATH
        env:
          BUILD_DIR: "${{ github.workspace }}"

      - name: Run specs
        run: bundle exec sass-spec.rb --impl libsass -c ../sassc/bin/sassc
